apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: warehouse-net-ca
  namespace: warehouse-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: warehouse-net-ca
  chart:
    git: git@github.com:innomizetech/blockchain-automation-framework.git
    ref: develop
    path: platforms/hyperledger-fabric/charts/ca    
  values:
    metadata:
      namespace: warehouse-net
      images:
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
        ca: hyperledger/fabric-ca:1.4.8
    deployment:
      annotations:
    annotations:  
      service:
        - example1: example2
      pvc:
       
    server:
      name: ca
      tlsstatus: true
      admin: warehouse-admin
    storage:
      storageclassname: warehousesc
      storagesize: 512Mi
    vault:
      role: vault-role
      address: http://192.168.50.152:8200
      authpath: devwarehouse-net-auth
      secretcert: baf-secret/crypto/peerOrganizations/warehouse-net/ca?ca.warehouse-net-cert.pem
      secretkey: baf-secret/crypto/peerOrganizations/warehouse-net/ca?warehouse-net-CA.key
      secretadminpass: baf-secret/credentials/warehouse-net/ca/warehouse?user
      serviceaccountname: vault-auth
      imagesecretname: regcred
    service:
      servicetype: ClusterIP
      ports:
        tcp:
          port: 7054
    proxy:
      provider: haproxy
      type: peer
      external_url_suffix: org2ambassador.blockchaincloudpoc.com
